@startuml Spring 2022 Desired HL Archiecture 
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include FONTAWESOME/users.puml
!include DEVICONS/react.puml
!include DEVICONS/dotnet.puml
!include DEVICONS/mongodb.puml
!include DEVICONS/firebase.puml
!include DEVICONS/python.puml
!include DEVICONS/redis.puml

Person(users, "UCI Students", $sprite="users")
System_Boundary(atpwy, "Anteater Pathway") {
    Container(spa, "Single Page Application", "Javscript, Next JS", $sprite="react")
    Container(planner_api, "Planner API", "C#, ASP.NET Core", $sprite="dotnet")
    ContainerDb(planner_db, "Planner Database", "Mongo DB", $sprite="mongodb")
    Container(course_api, "Course API", "Python, Fast API", $sprite="python")
    ContainerDb(course_db, "Course Database", "Reddis or MongoDB", $sprite="redis")
}

System_Ext(firebase_auth, "Firebase", "Google Authentication Service", $sprite="firebase")
System_Ext(cron, "cron-job.org", "Automatic Task Scheduler")

Rel(users, spa, "Uses", "a browser, HTTPS")
Rel(spa, planner_api, "Makes requests to", "JSON/HTTPS")
Rel(spa, course_api, "Makes requests to", "JSON/HTTPS")
Rel(planner_api, planner_db, "Reads/Writes")
Rel(course_api, course_db, "Reads/Writes")
Rel_R(cron, course_api, "Makes periodic requests to", "HTTP")
Rel_R(spa, firebase_auth, "Authenticates users with", "JWT")
@enduml